server:
  port: 8764

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_cloud_admin?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: yang
    druid:
      initial-size: 3
      max-active: 10
      min-idle: 3
  redis:
    host: 192.168.100.85
    port: 6379
    timeout: 3000
redis:
  cache:
    key-serializer: string
    value-serializer: genericjackson2json
    hash-key-serializer: string
    hash-value-serializer: genericjackson2json
    default-expiration: 30
logging:
  level:
    root: info
    org.mybatis: info
    cn.com.ylpw: debug
    com.mysql.jdbc: info
pagehelper:
  reasonable: false
security:
  ignored:
    - "/css/**"
    - "/js/**"
    - "/images/**"
    - "/webjars/**"
    - "/**/favicon.ico"
    - "/api/**"
    - "/test/**"
    - "/home"
  user:
    name: luobo
    password: 123